- hosts: tag_instance_filter_three_tier_app_matt_chan_solista_com_au
  gather_facts: false
  tasks:
  - name: Check the instances status
    wait_for:
      host: "{{ item }}"
      port: 22
      search_regex: OpenSSH
      timeout: 600
    delegate_to: localhost
    with_items:
      - "{{ inventory_hostname }}"
        