- hosts: frontends
  gather_facts: false

  tasks:
  - name: Open website
    uri:
     url: "http://{{ item }}"
     return_content: yes
    with_items:
      - "{{ inventory_hostname }}"
    register: webpage
    tags:
      - osp.smoke

  - name: Fail if we don't see 'Ansible has done its job' on the page
    fail:
    when: "'Ansible has done its job' not in webpage.results[0].content"
    tags:
      - osp.smoke