---
- name: Enable YUM Repos
  template:
    src: repos_template.j2
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644

- name: Install core tools
  yum:
    name: "httpie,python-pip" 
    state: latest
